version: '3'

services:
  order.webapi:
    image: order.webapi
    build:
      context: .
      dockerfile: ordering/Order.WebApi/Dockerfile   
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"      
      - "5672:5672"